### ISSUE TITLE
Implement `JsonGenerator.writeStartArray(int)`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-cbor#1]
When `jackson-core` adds the new variant of `writeStartArray`, CBOR module should implement it, at least for cases where length is small enough and we can save one byte from encoded length. Ideally we should also verify that actual number of value writes matches to indicated length.

**Comment by viktorklang** [comment]
@cowtowncoder Is this feature something that is implementable at the moment?

**Comment by cowtowncoder** [comment]
I don't see a fundamental reason why it couldn't be. Most that is needed is just to keep count of entries and verify that matching END_ARRAY matches with expected count, I think.
I think I had a quick look at some point, but didn't have time to actually do it; it wasn't trivial to do, needing bit more time/thought. But protobuf codec does something similar already, and I think Avro one as well.

**Comment by viktorklang** [comment]
@cowtowncoder Thanks for the update, whenever I may find a couple of hours to spare I'll see if I can take a stab at this.

**Comment by viktorklang** [comment]
@cowtowncoder Thanks for the update, whenever I may find a couple of hours to spare I'll see if I can take a stab at this. :tumbleweed: :)

**Comment by cowtowncoder** [comment]
Moving to https://github.com/FasterXML/jackson-dataformats-binary/issues/1 to consolidate as multi-maven repo for more efficient release process.
