### ISSUE TITLE
Array and Map (Object) with finite length

### ISSUE THREAD

**Issue by mbaril** [FasterXML/jackson-dataformat-cbor#11]
It would be great to add the possibility to encode array and map with finite length.

**Comment by cowtowncoder** [comment]
Yes that would be nice. Related to #1, which is required to make this happen efficiently -- problem being that the length of length marker itself is variable; and due to buffering which means that unless length is known a priori, buffering would otherwise pin down potentially vast amounts of memory.

**Comment by mbaril** [comment]
My comment was only for size that are known a priori. 

The method ```writeStartArray(int size)``` exists but the size is not used and the indefinite length form is used.
Also there is no such method for map (like ```writeStartObject(int size)```)

**Comment by cowtowncoder** [comment]
@mbaril yes, I  know of the state of `writeStartArray`, having added the method myself few months back. And this is why I referred to #1.

I was trying to think of whether similar would make sense for Object, and decided against addition.
Benefits seem much more modest for that, and additions to core `JsonGenerator` API are somewhat intrusive.
In both cases Jackson itself won't really benefit much, although there is one-byte size reduction for smallest arrays/objects. But I assume decoders on other platforms might benefit from being able to pre-allocate space or such,.

Anyway, addition for arrays is more practical, if anyone wants to tackle it.

**Comment by nicorikken** [comment]
+1 as we encountered this in development: the CBOR gem https://github.com/cabo/cbor-ruby for ruby only supports arrays and maps of finite length. This renders these Java (+ Clojure) and Ruby implementations incompatible.

**Comment by cowtowncoder** [comment]
I would argue that ruby implementation is actually broken, if so -- I don't see how a specification-compliant codec could refuse to decode valid content. So I would file a bug against those.

Having said that, I am not against adding support for producing known-length arrays and objects if and as feasible. Arrays should be significantly easier to support efficiently, although in practice objects may be feasible for common cases. The main downside is that it is impossible to write any of enclosed content until all of it has been buffered, and (logical) length known.
