### ISSUE TITLE
Add a public `finishToken()`

### ISSUE THREAD

**Issue by philipa** [FasterXML/jackson-dataformat-cbor#20]
I'm using a CBOR parser in conjunction with byte-wise operations on the underlying buffer.

I'd like a way to force the current token to be consumed (pretty much what  `_finishToken()` does}. Right now I'm using `getTextCharacters()` as a workaround.

**Comment by cowtowncoder** [comment]
Ok makes sense. Perhaps exposing method `public finishToken()` would make sense; first for `CBORParser`, and later on (if it seems useful for at least one other backend) possibly via `JsonParser`.
This would go in 2.8 since it's API change.

**Comment by philipa** [comment]
Thanks, that would be welcome.

**Comment by cowtowncoder** [comment]
I added `public finishToken()` for now (2.7.2), will add in `JsonParser` in 2.8.
