### ISSUE TITLE
String value can only be read as Field Name

### ISSUE THREAD

**Issue by andrey-polyakov** [FasterXML/jackson-dataformat-cbor#21]
Hi,

I wrote some unit tests to illustrate my concern.
Thanks.
```


    @Test
    public void thisFails() throws IOException {
        ByteArrayOutputStream out = new ByteArrayOutputStream(16);
        CBORGenerator cbor = cborFactory.createGenerator(out);
        cbor.writeStartArray();
            cbor.writeStartObject();
                cbor.writeString("BAR");
                cbor.writeStartArray();
                cbor.writeEndArray();
            cbor.writeEndObject();
        cbor.writeEndArray();
        cbor.close();

        byte[] encoded = out.toByteArray();

        CBORParser parser = cborFactory.createParser(encoded);
        parser.nextToken();
        assertEquals(JsonToken.START_ARRAY, parser.getCurrentToken());
            parser.nextToken();
            assertEquals(JsonToken.START_OBJECT, parser.getCurrentToken());
                parser.nextToken();
                assertEquals(JsonToken.VALUE_STRING, parser.getCurrentToken());
                assertEquals("BAR", parser.getText());
                parser.nextToken();
                assertEquals(JsonToken.START_ARRAY, parser.getCurrentToken());
                parser.nextToken();
                assertEquals(JsonToken.END_ARRAY, parser.getCurrentToken());
            parser.nextToken();
            assertEquals(JsonToken.END_OBJECT, parser.getCurrentToken());
        parser.nextToken();
        assertEquals(JsonToken.END_ARRAY, parser.getCurrentToken());
    }

    @Test
    public void thisWorksThough() throws IOException {
        ByteArrayOutputStream out = new ByteArrayOutputStream(16);
        CBORGenerator cbor = cborFactory.createGenerator(out);
        cbor.writeStartArray();
        cbor.writeStartObject();
        cbor.writeString("BAR");
        cbor.writeStartArray();
        cbor.writeEndArray();
        cbor.writeEndObject();
        cbor.writeEndArray();
        cbor.close();

        byte[] encoded = out.toByteArray();

        CBORParser parser = cborFactory.createParser(encoded);
        parser.nextToken();
        assertEquals(JsonToken.START_ARRAY, parser.getCurrentToken());
            parser.nextToken();
            assertEquals(JsonToken.START_OBJECT, parser.getCurrentToken());
                parser.nextToken();
                assertEquals(JsonToken.FIELD_NAME, parser.getCurrentToken());
                assertEquals("BAR", parser.getCurrentName());
                parser.nextToken();
                assertEquals(JsonToken.START_ARRAY, parser.getCurrentToken());
                parser.nextToken();
                assertEquals(JsonToken.END_ARRAY, parser.getCurrentToken());
            parser.nextToken();
            assertEquals(JsonToken.END_OBJECT, parser.getCurrentToken());
        parser.nextToken();
        assertEquals(JsonToken.END_ARRAY, parser.getCurrentToken());
    }
```

**Comment by andrey-polyakov** [comment]
Please check out a unit test called HystrixRequestEventsCborStreamTest.testSingleSuccessFromCbor
in [here](https://github.com/andrey-polyakov/Hystrix). You want to look into [this revision](https://github.com/andrey-polyakov/Hystrix/commit/473a0fe328867c26f454212cdaf62f192b00f669).

Looks like an error in the library. I double checked and concluded it ought to read my stuff from CBOR but it breaks...

Thanks.

**Comment by cowtowncoder** [comment]
Thanks, I'll have a look.

I did notice a minor flaw in generation where:

```java
        cbor.writeStartObject();
            cbor.writeString("BAR");
```

should fail as Jackson's generator expects use of `writeFieldName()`, but I assume this is not the main issue here (since CBOR does not distinguish field name values).

**Comment by andrey-polyakov** [comment]
@cowtowncoder I didn't know that and that's weird. Why does it expect field name? Can one omit filed names altogether just to save some space?

Have you checked that revision? In there something off is going on (maybe because my expectations are different though).

Thanks.

**Comment by cowtowncoder** [comment]
@andrey-polyakov No, it's the Jackson model of JSON streaming data -- Objects contain sequences of FIELD_NAME / value pairs. While JSON encoding of keys is same as for Strings. Given this, generator _should_ require similar checks, but I perhaps not all do. Model could have been done differently too, by using only one token type for both; but at this point it is the way it is.

Anyway, I haven't looked at the fail yet, hoping to do so later today. This could be something unrelated.

**Comment by cowtowncoder** [comment]
Actually invalid write is caught with 2.7, so I can not reproduce that problem.

Otherwise, I am not actually quite sure what you think is not working here: Objects will expose FIELD_NAME tokens for names, and VALUE_STRING for values of type String. Arrays have no fields, only elements, so they will expose VALUE_STRINGs.

**Comment by andrey-polyakov** [comment]
Right, I got the point JSON encoding, so then generator should perform the very same checks as the parser does. Even once I was violating key-value model I still expected something successfully encoded to be decoded back. 

Actually, it would be useful if this could be violated on purpose by generator/parser setup. I do understand though that would be distinct from CBOR format.

Thanks. You can close the ticket then.

**Comment by cowtowncoder** [comment]
@andrey-polyakov Ok thanks. Just wanted to make sure I did not miss some other problem in the test.
And I agree in that something that is successfully encoded should be possible to decode.

For what it is worth, limits on valid sequences are indeed enforced (or not) by parser/generator implementations, so some formats may allow other kinds of sequences. While this may be problematic for databinding (which tries to remain format-agnostic), it can be useful for some backends; specifically XML module has a few work-arounds to adapt XML infoset into JSON-like token stream.
