### ISSUE TITLE
Overflow when decoding uint32 for Major type 0

### ISSUE THREAD

**Issue by TianlinZhou** [FasterXML/jackson-dataformat-cbor#25]
When decoding unit32 that is larger than 2^31 - 1, overflow will happen.
For example, decoding "1a 8a e8 08 f1" will get -1964504847, but it should be 2330462449.

**Comment by cowtowncoder** [comment]
My mistake in suggesting this tracker: moved to https://github.com/FasterXML/jackson-dataformats-binary/issues/30 which is the new repo that combines binary codecs.

Thank you for reporting this!
