### ISSUE TITLE
Infinite loop when trying to write binary data using CBORGenerator

### ISSUE THREAD

**Issue by mbaril** [FasterXML/jackson-dataformat-cbor#9]
The function ```public int writeBinary(InputStream data, int dataLength)``` can ends up in an infinite loop.

```
private final int _writeBytes(InputStream in, int bytesLeft) throws IOException
    {
        while (bytesLeft > 0) {
            int room = _outputEnd - _outputTail;
            if (room < 0) {
                _flushBuffer();
                room = _outputEnd - _outputTail;
            }
            int count = in.read(_outputBuffer, _outputTail, room);
            if (count < 0) {
                break;
            }
            _outputTail += count;
            bytesLeft -= count;
        }
        return bytesLeft;
    }
```

If variable room is equal to 0, the in.read method will also return 0. In this case the function never return.

I think that ```if(room<0)``` should be replaced by ```if (room<=0)```

**Comment by mbaril** [comment]
I've created a pull request that include the fix for this issue (and unit tests)

**Comment by cowtowncoder** [comment]
Great!

If we haven't yet asked for (and received) a CLA, the next step is to print out, fill, scan and email this:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

to `info` at fasterxml.com. With that I can merge in the code submission.

**Comment by cowtowncoder** [comment]
Nasty bug. Thank you for the contribution; I backported it in 2.3 and 2.4 as well.

It also made it right in 2.5.1, which just got released.
